name: Flutter Nightly Build (Windows Only)

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      upload-artifact:
        type: boolean
        default: true
        description: "Upload artifacts"
      upload-tag:
        type: string
        default: "nightly"
        description: "Upload tag"

jobs:
  run-flutter-nightly-windows-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: ${{ inputs.upload-artifact || true }}
      upload-tag: ${{ inputs.upload-tag || 'nightly' }}
      build-target: "windows"

