name: Flutter Nightly Build

on:
  workflow_dispatch:
    inputs:
      upload-artifact:
        type: boolean
        default: true
        description: "Upload artifacts"
      upload-tag:
        type: string
        default: "nightly"
        description: "Upload tag"
      build-target:
        type: choice
        default: "all"
        description: "Build target platform"
        options:
          - all
          - windows
          - macos
          - linux
          - android
          - ios
          - web

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: ${{ inputs.upload-artifact || true }}
      upload-tag: ${{ inputs.upload-tag || 'nightly' }}
      build-target: ${{ inputs.build-target || 'all' }}
